# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ciciolog
email: maciej@jagiello.it
description: > # this means to ignore newlines until "baseurl:"
  Yet another geek''s blog. Gamedev, FOSS, ranting and beer tasting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ciciolog.jagiello.it" # the base hostname & protocol for your site
twitter_username: ciciocian
github_username:  cician

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge